Universe	= vanilla
# Request 1 CPU for this job
RequestCpus	= 1
# Request at least 10G CPU memory for this job
RequestMemory	= 10G
# Allow this job to run for a maximum of 360000s
+RequestWalltime	= 360000 

# Request 1 GPU for this job
request_GPUs	= 1
# Request at least 7.5G RAM GPU memory for this job
requirements	= (CUDAGlobalMemoryMb >= 7500) && (CUDACapability >= 3.5) && (has_avx == True)

# Execute job as a nice user
NiceUser = true
# Mail me only if something is wrong
Notification = Error

# Start job from current directory
initialdir = /users/students/r0691656/r0691656/exp/master_thesis/condor
# Execute shell file
executable = /users/students/r0691656/r0691656/exp/master_thesis/condor/train_cross_val.sh

# Define paths for log, output and error files, allowing you to debug and read output of your jobs.
Log          = condor/cross_val_logmel.log
Output       = condor/cross_val_logmel.out
Error        = condor/cross_val_logmel.err

should_transfer_files = YES

# Start just 1 instance of the job
Queue 1
